### ISSUE TITLE
Null Safety Migration

### ISSUE THREAD

**Issue by TimWhiting** [leisim/dartx#112]
Just wanted to open an issue for this since null safety is now in [beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730) and they are encouraging package authors to migrate.

A quick check with `pub outdated --mode=null-safety` shows that `crypto` and `time` still need to update before this package probably should.
```
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name  Current  Upgradable  Resolvable             Latest                 

direct dependencies:
characters    -        ✗1.0.0      ✓1.1.0-nullsafety.5    ✓1.1.0-nullsafety.5    
collection    -        ✗1.14.13    ✓1.15.0-nullsafety.5   ✓1.15.0-nullsafety.5   
crypto        -        ✗2.1.5      ✗2.1.5                 ✗2.1.5                 
meta          -        ✗1.2.4      ✓1.3.0-nullsafety.6    ✓1.3.0-nullsafety.6    
path          -        ✗1.7.0      ✓1.8.0-nullsafety.3    ✓1.8.0-nullsafety.3    
time          -        ✗1.3.0      ✗1.3.0                 ✗1.3.0                 

dev_dependencies:
fake_async    -        ✗1.1.0      ✓1.2.0-nullsafety.3    ✓1.2.0-nullsafety.3    
pedantic      -        ✗1.9.2      ✓1.10.0-nullsafety.3   ✓1.10.0-nullsafety.3   
test          -        ✗1.15.5     ✓1.16.0-nullsafety.10  ✓1.16.0-nullsafety.10  

No pubspec.lock found. There are no Current versions.
Run `pub get` to create a pubspec.lock with versions matching your pubspec.yaml.

7  dependencies are constrained to versions that are older than a resolvable version.
To update these dependencies, edit pubspec.yaml.

```

**Comment by passsy** [comment]
It would be awesome if you could also reach out to those projects :)

**Comment by leisim** [comment]
I created a [nnbd branch](https://github.com/leisim/dartx/tree/nnbd). We're just waiting on some transitive dependencies now.

**Comment by shinayser** [comment]
@leisim Time has been already updated to NNDB. Seems that only `crypto` is missing, right?

**Comment by TimWhiting** [comment]
By the way crypto was just published, so this should be unblocked

**Comment by AKushWarrior** [comment]
NNBD for this package should be pretty easy since it's mostly methods. I can take a crack at it if it's not already been done.

**Comment by atreeon** [comment]
Hi, is there an update?  I think the dependencies have been updated now?

**Comment by shinayser** [comment]
@leisim @passsy guys,why don't you add another admin to the project? Seems that you guys can't spend much time improving, accepting PRs, upgrading libs, etc... The project is starting to look a little "abandoned" 
If there is anything we can do for you, please just ask!

**Comment by shinayser** [comment]
Guys @leisim @passsy ? March 3 is about the corner. You got any news?

**Comment by passsy** [comment]
`0.6.0` has been published with nullsafety enabled.

I'm sorry for the delay to actually publish this nnbd version. While migrating we noticed that other packages, especially [`package:collection`](https://pub.dev/documentation/collection/1.15.0/collection/IterableExtension.html) started shipping their own extension functions. Those, in the long-term, will make `dartx` obsolete.

The big question was, whether we want to expose those extension methods through `dartx`, as we do with the `time` and `characters` package. But when I tried I ran into multiple naming conflicts, which would 1. be a breaking change, 2. could cause many more breaking changes down the line when more extensions get added.

### Future

I'm missing a long-term goal for this project and a clear scope for 1.0. That's why merging becomes slower. The more methods we add, the harder it gets to prevent conflicts. If we blindly add everything, this project becomes a mess of methods nobody actually uses (remember [quiver](https://github.com/google/quiver-dart)?). And we have no way of telling which methods are actually used.

For the time being, I can only encourage everyone here to contribute new extensions to specialized packages with a clear scope.
