### ISSUE TITLE
No more updates ?

### ISSUE THREAD

**Issue by mobiluse** [leisim/dartx#170]

**Comment by ilovelinux** [comment]
What would you expect from a new update?

- If you want a feature request, please open an issue about that. Maintainers will take into consideration that.
- If you found a bug, please open an issue about that. Someone will fix it soon!

As far as I understand (I'm not a maintainer) there's actually no need to release an update because everything works fine. 🙂

**Comment by passsy** [comment]
100% correct @ilovelinux

The last release was `v1.2.0` on 18th July 2023, less than a month ago. I'm not sure what you expect @mobiluse.
