### ISSUE TITLE
Best extension design?

### ISSUE THREAD

**Issue by ChaserVasya** [leisim/dartx#174]
This lib has next extension namings
```
SomeNameX
ClassMethodExtension
Method
```

Also, some extensions have one method, while others have several.

What's better?

This will be useful for the community when developing extensions.

**Comment by passsy** [comment]
#122 might be interesting for you. We moved from having one extension per type to one extension per function.

The reasoning is: 
- Some extensions might name-clash with other packages
- You want to individually hide/show single extensions while hide/show all others

For the extension name we usually only use the function name in dartx, because every extension only has a single function.

I personally hate that I have to come up with a name at all. The name could be technically derrived from the extension itself like in Kolin.
See the discussion at https://github.com/dart-lang/language/issues/1627
