### ISSUE TITLE
Transform paramenter on "windowed' should not be required

### ISSUE THREAD

**Issue by shinayser** [leisim/dartx#19]
Hello!
Most of time when using the `windowed` method you just want to go through the list, without worring about its transformation. But the current api has the transform method required, wich leads to some silly usages like:

```dart
var myList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
myList.windowed(3, (win) => win).forEach( ...)
```

I suggest making it optional, just like the `step` and `partialWindows` are, with a default value return the current iteration object, just like the sample above.

Like this:
```dart
myList.windowed(3, transform: (win) => win).forEach( ...)
```

Of course this is a breaking change, but well documented in the change logs will not cause much problem.

What you think?

**Comment by passsy** [comment]
This is a harder problem than it initially seems like. Let's look at the signature.

```dart
Iterable<R> windowed<R>(
    int size,
    R transform(List<E> window), {
    int step = 1,
    bool partialWindows = false,
})
```

The transform function `R transform(List<E> window)` changes the return type. `R` is only defined in the `transform` parameter. Without defining `transform` dart static analysis can't tell the type of `R` and the returned typed would be `Iterable<dynamic>`. That's not what we want, it should be `Iterable<List<E>>` by default.

There are three solutions to the problem:

### Default function
We could define a default parameter `R transform(List<E> window) = (list) => list`. This is how Kotlin does it. But lambdas aren't constant and can't be used as default parameters in dart. See https://github.com/dart-lang/sdk/issues/4596

### Remove transform

My gut feeling tells me that the majority of users doesn't need the `transform` parameter. Removing it is not a big problem because it can be replaced with a `map` function afterwards.

```diff
--[0, 1, 2, 3, 4, 5].windowed(1, (list) => list)
++[0, 1, 2, 3, 4, 5].windowed(1).map((list) => list.first)
```

### Two methods

I created two methods in `ktdart` one with and one without the `transform` parameter to fix static typing.

```dart
KtList<KtList<T>> windowed(int size,
      {int step = 1, bool partialWindows = false})

KtList<R> windowedTransform<R>(int size, R Function(KtList<T>) transform,
      {int step = 1, bool partialWindows = false})
```

So far I haven't seen anyone using `windowedTransform`. That's why I prefer to remove the `transform` parameter

**Comment by shinayser** [comment]
I vote for **removing the transform parameter**. As you said, it can easily fixed by a map function.

**Comment by leisim** [comment]
I agree. Let's remove it.
