### ISSUE TITLE
About the duplicated methods...

### ISSUE THREAD

**Issue by shinayser** [leisim/dartx#49]
Originally this issue was to discuss the need of the `coerceIn` method, but before I searched on the issues history and found that this issue already exists https://github.com/leisim/dartx/issues/18.
The argument that @leisim used on it is pretty valid as it helps other developers from other languages to find more easily some of their correspondents on dart language.

But this causes a problem: **too many methods on the auto complete window that does the same thing**.

And if you allow me to question: why we are only providing methods for the Kotlin users? Why not provide also duplicated methods for Swift, Javascript, PhP, Python, c++... see my point?

But I think I have a nice sollution for this problems and would like to hear other collaborators thoughts:
- Instead of providing methods that does the same thing of the Dart method's, we could add a section to the README file that does a one-to-one correspondency to other languages methods.

This would resolve the methods overflooding and also help other developers to find correspondents on the Dart language.

What you ~guys~ folks think?

**Comment by leisim** [comment]
> too many methods on the auto complete window that does the same thing

We don't try to add all method names possible, just the very popular ones like `filter()`. If you come from Kotlin, you kind of expect Dart to have a filter method ^^

> Why not provide also duplicated methods for Swift, Javascript, PhP, Python, c++

That is a valid point. I would suspect that most of the users of Flutter are familiar with Kotlin. But a substantial amount also has an iOS or web background so I think we should also allow pull requests for "super popular" methods from Swift and JS. Since my personal background is Android, I invite everyone who can't live without a method from another language to create a pull request. It should however fit into the Dart ecosystem.

> we could add a section to the README file that does a one-to-one correspondency to other languages methods

Great idea. Not sure if the README is the right place for that. Maybe we can mention popular methods of other languages in the documentation of the corresponding `dartx` extension. This would allow to find it via search.

**Comment by shinayser** [comment]
> This would allow finding it via search.

Adding it to the README file is much easier to find it because all the methods will be on the same page. Adding it to the `dartx` documentation would be a problem because every method is separated by contexts, separated by different files.

That is why I am suggesting to add it to the a README section "Methods correspondency", a Ctrl + F would solve this problem in an easier way.

>  I think we should also allow pull requests for "super popular" methods from Swift and JS

This would only increase even more the problem for the auto complete flooding. This doesn't bother you?

**Comment by leisim** [comment]
> This doesn't bother you?

I don't have any problems with auto-complete. What problems do you experience?

**Comment by passsy** [comment]
> And if you allow me to question: why we are only providing methods for the Kotlin users? Why not provide also duplicated methods for Swift, Javascript, PhP, Python, c++... see my point?

Kotlin is relatively new and the the language designers had the chance to created an elegant API by combining the best APIs from tons of other languages (Java, Scala, C#, Groovy, Python, Nice) [as mentioned by Andrey Breslav](https://2018.geekout.ee/andrey-breslav/). So it's not that we favour the Kotlin API per se, but a naming convention which is common across many languages.

The Kotlin API isn't perfect though. The language has features which do not exist in Dart (more operators to overload, infix notation, method/constructor overloads) and vice versa. This is where we together have to fill the gap with good names inspired from any language.

In the end, all **I** want is making programming as easy as possible. This also means instead of closing 20 issues/PRs pointing people to the correct method, I add the alias. I don't want fights about the naming of a method. Depending on ones background and the task at hand the other name might be actually a better fit.

Speaking of [`clamp`](https://github.com/leisim/dartx/issues/18), I'm happy to add an alias for `coerceIn` (which I'm not even able to pronounce). But as I understood it, the initial issue was questioning why we even added `int.coerceIn(min, max)`, `int.coerceAtLeast(min)` and `int.coerceAtMost(max)` extensions instead of using the `dart:core` `clamp(min, max)`, `min(a, b)` and `max(a, b)` methods. This doesn't make a lot of sense because it questions the existence of this whole project or the static extensions method language feature.

> But this causes a problem: **too many methods on the auto complete window that does the same thing.**

I don't see it as a big problem. If it becomes one we can deprecate rarely used duplicates so that they are recommended last. Or even add a custom annotation which helps ranking them (which should be relatively easy to implement by the IDE plugin maintainers). Dart recently added machine learning to improve auto-completion. I'm confident we figure something out.

**Comment by yongjhih** [comment]
We can split those duplicated methods into other flavored packages if they are really unnecessary.
